### ISSUE TITLE
Is the main navigation bar height correct ?

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#116]
I've taken [this page](https://design.smart.coop/development/template-examples/app-form.html) as-is and removed the main content, i.e. the part that starts with

```
    <main class="u-scroll-wrapper u-maximize-width">
```

When I do so, the resulting main navigation bar is slightly taller than it appears on the complete page. I guess the main content overlaps it a bit. Is it possible to make sure the main navigation bar alone has the same height ?

**Comment by Wolfr** [comment]
The height is based off of its elements, this is normal. If we give it a fixed height, we break its responsive flexibility. I can check this however next time I am working on the code.
