### ISSUE TITLE
Is it normal that toplevel items in the navbar hierarchy have a href ?

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#135]
If I look at the source of e.g. this page https://design.smart.coop/development/template-examples/app-form.html, the 'Management" link has a `href`, and when I click on it, in addition of opening the menu, this also adds a `#` to the URL (which is the value of the `href`). I guess this is a small bu in the way the menu code is working (this shouldn't make any change to the URL until I select a sub-item).

**Comment by Wolfr** [comment]
These should be a `button` (with action to open the submenu,) using an `<a>` with a `#` link is a way we've implemented it many times but it's technically wrong.

**Comment by thusc** [comment]
I think this is good now. Thanks a lot.
