### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#16]
Proposal: to change repo name from `design` to `smartcoop-design-system` so it makes sense next to all my other git repos.

Feedback wanted @thusc

**Comment by thusc** [comment]
You can name your local directory however you want, e.g.:

```
$ git clone git@github.com:smartcoop/design.git smartcoop-design-system
Cloning into 'smartcoop-design-system'...
```

And you can rename it afterwards, no need to clone it again.

An alternative scheme is to name repositories with the username/organization (i.e. add a parent `smartcoop` directory).

Or do you really want the local name to match the GitHub name ?

**Comment by Wolfr** [comment]
I know you can just make a local change. It's a small comment, if you don't agree, I'm OK with that. I'll let it slide.

Just to write about how I work.

I have a `~/Sites` folder with 100+ projects. I prefer if the repo name contains the project name and not something like `design`.

I guess I can solve it by having a `smartcoop` folder in there. The thing is that this doesn't help for my other workflow using Tower which lists the repo in a singular list.

<img width="406" alt="CleanShot 2021-08-13 at 13 42 38@2x" src="https://user-images.githubusercontent.com/12690/129352297-6daef27e-fa3c-4fdb-989e-cb440a8288f3.png">

I typically move the repos that I am actively working on to the top.

**Comment by thusc** [comment]
I guess Tower, and your `~/Sites` would be totally ok with just renaming the local directory how you want (without introducing a parent directory). Repositories actually don't have any names...
