### ISSUE TITLE
Avatar: incorrect documentation regarding css classes

### ISSUE THREAD

**Issue by maxime-poulain** [smartcoop/design#162]
Hello,
the class c-avatar--regular doesn't exist
![image](https://user-images.githubusercontent.com/90202188/142241562-639417c3-0e7e-47d4-9847-84db5d306c74.png).

However the following one do exist:
* .c-avatar--small
* .c-avatar--medium
* .c-avatar--large 
![image](https://user-images.githubusercontent.com/90202188/142241679-d8b1b09a-748e-4f2d-b7de-0a8fee107d73.png)

**Comment by emilyvandewalle** [comment]
The unused class `c-avatar--regular` has been removed from the avatar mixin/documentation

**Comment by maxime-poulain** [comment]
Ty.
