### ISSUE TITLE
Improve tag design scannability

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#165]
Improve tag design scannability

I don't like the tag design. Normally a colour can symbolize a clear status. Like here on Unsplash:

<img width="985" alt="Screen Shot 2021-11-22 at 20 07 06" src="https://user-images.githubusercontent.com/12690/143443991-e8fa4e97-6e00-4351-92f1-efd2d7150c44.png">

However with the current design, there is only a very small “dash” of colour to see, ad it's hard to scan by colour.

Example:

<img width="852" alt="Statistics 101" src="https://user-images.githubusercontent.com/12690/143444011-f41b0598-6a9c-4bf6-8f15-33d5133660eb.png">

Any thoughts?

**Comment by emilyvandewalle** [comment]
I see, not sure if entirely related, but I had a similar issue with the warning alert not having a lot of visual weight 
![image](https://user-images.githubusercontent.com/36261498/144263347-8fa780e6-dcf8-494b-8a6b-3cbbb1d9813c.png)

I did some quick explorations for the tags and was thinking to either use a similar style as Unsplash with a lighter background:
![image](https://user-images.githubusercontent.com/36261498/144264514-3fcefa1f-1474-4495-8ef2-613c776bc39e.png)

Use the color as background color (tried the darker blue here to have enough contrast):
![image](https://user-images.githubusercontent.com/36261498/144265074-3f4349b4-4abd-496d-905d-bb490a70fbce.png)

Or use the color for the text inside the tag too:
![image](https://user-images.githubusercontent.com/36261498/144265290-eeee0ee0-9785-4b79-b596-98b4fab3d3a0.png)

What do you think?

**Comment by thusc** [comment]
Just a personal taste, but definitely the Unsplash like one. I think it's a bit more subtle but quite readable and I like the little dot.

**Comment by Wolfr** [comment]
@emilyvandewalle Good comment, maybe we should change parts of the design to use more pastel-like colors. It will look a bit like Bootstrap then but I think usability comes first.

**Comment by emilyvandewalle** [comment]
Sounds good, I'll take a look to update both the status tags and alerts to more pastel-like colors

I made a proposal for the alerts too, what do you think?
![image](https://user-images.githubusercontent.com/36261498/144467231-ee0dea9d-76c0-47b7-83af-b05920b814b8.png)

This means I'll have to add some extra colors  (a `color-...-50` and `color-...-700` variant for each)
I'll make sure to document it
