### ISSUE TITLE
Clicking on a dropdown menu doesn't close open one(s)

### ISSUE THREAD

**Issue by maxime-poulain** [smartcoop/design#176]
Hello,
when a user clicks on a dropdown menu, the dropdown is displayed correctly, if he clicks on another, the previous one stays open.
![image](https://user-images.githubusercontent.com/90202188/144259996-1b3c0d4f-f737-457f-8762-91dae7de9487.png)

**Comment by Wolfr** [comment]
As reported in #55 but good to have a reminder, this has been bothering me every since I implemented it.

**Comment by maxime-poulain** [comment]
Ty.
