### ISSUE TITLE
[Request] Add a generic for not found and error page

### ISSUE THREAD

**Issue by maxime-poulain** [smartcoop/design#177]
Hello,

having a re-usable page when a  user a non existing url would be cool.
Also having another one for error such internal server error (500) could be nice.
Maxime.

**Comment by emilyvandewalle** [comment]
I have added the component for the error page here: https://design.smart.coop/development/docs/c-error-page.html

Here's an example of a 404 page: https://design.smart.coop/template-examples/404.html
