### ISSUE TITLE
Use a Smart favicon

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#18]
The default Mono favicon is used. A SmartCoop favicon needs to be added.

**Comment by thusc** [comment]
I think you have access to this internal repository, and thus to https://github.com/smartcoop/common-assets/tree/master/favicon.

If you need an original red "S" alone in SVG, it is here: https://github.com/smartcoop/common-assets/blob/master/img/smart-logo/smart-capital-s.svg

Let me know if you need something else.

**Comment by thusc** [comment]
If you copy the whole `favicon/` directory over here, can you create an additional issue here to track its deletion on the `common-assets` repository, to avoid duplication ?

**Comment by Wolfr** [comment]
@thusc the only thing we did now was swap the favicon, I think we just want the favicon.ico and nothing else, unless we also add an apple touch icon and more (which I would consider a separate issue).

Do we need to do anything else or can we consider this closed?

**Comment by thusc** [comment]
Yes, I'm closing it.
