### ISSUE TITLE
Example Pages: Contract list: Akward "c-panel_title" class attribute inside the tile.

### ISSUE THREAD

**Issue by maxime-poulain** [smartcoop/design#183]
![image](https://user-images.githubusercontent.com/90202188/146642522-1f9ae49a-f096-4b38-b8a1-d6a872ddf027.png)

I would have expected to have 
```html
<h4 class="c-card__title">Card title</h4>
```
Maxime.

**Comment by emilyvandewalle** [comment]
You are right, this should definitely have been a `c-card__title, should be updated now 👍
