### ISSUE TITLE
Missing textarea css selectors / classes

### ISSUE THREAD

**Issue by maxime-poulain** [smartcoop/design#185]
Hello as documented [here](https://design.smart.coop/development/docs/o-form-group.html) we can can display an error messages but also add css classes to add a border around elements/components that resulted into a failure.

However there is no c-textarea--error / or selector on form group > textarea to add the border to text areas

**Comment by emilyvandewalle** [comment]
Hi Maxime,

I have added the error styles for textareas as well now and added a textarea to the validation example in the documentation as well: https://design.smart.coop/development/docs/o-form-group.html#component-05-o-form-validation
