### ISSUE TITLE
Spacing utilities need to be documented

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#19]
* Spacing utilities need to be documented
* Should we rethink these to be number based? (1, 2, 3, 4, 5)
* Where the numbers tie back to a value (8px, 16px, 24px, 32px, 40px)?
* Currently we have `-s, [no prefix], -l, xl,`

Opinions welcome.

**Comment by thusc** [comment]
Personal opinion: I like the `8px` and so on naming scheme, unless you think their actual value could change without requiring to update their call sites.

**Comment by Wolfr** [comment]
https://design.smart.coop/styleguide/u-spacer.html

Thank you @emilyvandewalle
