### ISSUE TITLE
Review project picker pattern

### ISSUE THREAD

**Issue by emilyvandewalle** [smartcoop/design#200]
![image](https://user-images.githubusercontent.com/36261498/149564548-f977c0d9-013b-4baa-9300-c54d4efec135.png)

**Comment by emilyvandewalle** [comment]
@thusc For this I would propose this pattern, what do you think?
![image](https://user-images.githubusercontent.com/36261498/150790307-602bbe9f-7f05-408c-802f-680549f397f6.png)

**Comment by thusc** [comment]
I think it's nice, thank you. I guess this will need a bit of JS, which is ok. We can still use a simple link "Add new project" for the noJS POCs if we want.

**Comment by emilyvandewalle** [comment]
@thusc Thanks for the quick feedback! I have added an example on the page here: https://design.smart.coop/prototypes/old-desk/contract-create-1.html
