### ISSUE TITLE
Data selection in mixin (for <select>s)

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#21]
I have a bug with the countries object in my last version.

Essentially I am trying to you can create a “select” like  this:

```
  +c-form-group({ label: 'Sexe', id: 'tfGender', type: 'select', value: ['Masculin','Feminin','X']})
```

Here I am passing an array.

But for countries, the list is quite long, so I am passing an object which contains countries and countrycodes.

```
  +c-form-group({ label: 'Pays', id: 'tfAddressOfficalCountry', type: 'select', value: contentData.countries.all })
```

The data structure looks like this

```
module.exports = {
  popular: [
    {
      "countryCode": "GB",
      "countryName": "United Kingdom"
    },
    {
      "countryCode": "BE",
      "countryName": "Belgium"
    },
    {
      "countryCode": "NL",
      "countryName": "Netherlands"
    },
    {
      "countryCode": "DE",
      "countryName": "Germany"
    },
    {
      "countryCode": "FR",
      "countryName": "France"
    }
  ],
  all: [
    {
      "countryCode": "AD",
      "countryName": "Andorra"
    },
    {
      "countryCode": "AE",
      "countryName": "United Arab Emirates"
    },
    {
      "countryCode": "AF",
      "countryName": "Afghanistan"
    },
   ...
```

Now, how to select the `countryCode` key in an elegant way?

Or should I just simplify Countries to be an array instead...?

Related commit: https://github.com/smartcoop/design/commit/9ff644490cb6c4c58a1f251bc161ac65746c8396
Deploy link: https://design.smart.coop/subscription-form.html

**Comment by thusc** [comment]
So I have provided a fix. Indeed you could also have in `contentData.countries` various alternative lists of values but I would keep it the way you did it until (possibly) you find it cumbersome to use.
