### ISSUE TITLE
Bedrock: add slash to directories in the ctrl-m menu

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#35]
Within the main menu (the one accessible with `crtl-m`), the `styleguide` link doesn't have a slash at then end.

This mean that if the site is served by Nginx on port 80, but using a port forwarding with Docker on port 5000, it points to http://127.0.0.1:5000/styleguide.

By default, Nginx will redirect to the URL plus `/`. The problem is that Nginx (which doesn't know it is served through Docker) actually redirects to http://127.0.0.1/styleguide/ instead of http://127.0.0.1:5000/styleguide/ (i.e. without the port).

If Bedrock links to `/styleguide/`, I think the problem would disappear. Can we do that, or does it cause problems in other setups ?

**Comment by Wolfr** [comment]
I don't think this will cause a problem. But this seems like a change we should first make in Bedrock. I will make an issue and then whenever I work on Bedrock fix it.

**Comment by Wolfr** [comment]
Since we are not using the page tree anymore, the problem this issue describes doesn't occur anymore.
