### ISSUE TITLE
Bedrock: the `page-index` page has both `page-index` and `index` active

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#36]
In the main menu (the one accessible with the `ctrl-m` shortcut), the active page is highlighted. If the page is `page-index`, it highlights both `page-index` and `index`. See screenshot:
![screenshot](https://user-images.githubusercontent.com/45588452/130519066-e1b7dba1-73e4-4f8c-b164-cc66c44dad89.png)

**Comment by Wolfr** [comment]
This seems like a global Bedrock bug. I will make a bug in the Bedrock repository and link back here.
