### ISSUE TITLE
Gender field on subscription form

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#38]
Currently, the subscription form lists “Male”, “Female“ and “X”. This needs to be improved. What are the possible values for “Gender”?

Is it relevant to ask for this information when registering for Smart?

Possibly something to be passed to communications director.

Reference https://design-system.service.gov.uk/patterns/gender-or-sex/

**Comment by Wolfr** [comment]
Tackle this in design first see #40 .

**Comment by thusc** [comment]
- See this comment https://github.com/smartcoop/design/issues/39#issuecomment-904655094 for the general approach ("don't change anything")
- Specifically for this field, it is possible it is only used to address people in emails. So maybe an alternative would be "How do you want to be addressed", or simply to remove such question and make sure we can address people in a neutral way, e.g. "Dear Johan".

**Comment by Wolfr** [comment]
We can focus purely on the UI design/objective inherent qualities of the UI (i.e. a good layout, great focus states, a good looking grid etc.) and not on the content for now, if this is a conscious decision I am fine with that.
