### ISSUE TITLE
Vertical scrollbar should always appear (?)

### ISSUE THREAD

**Issue by thusc** [smartcoop/design#45]
When navigating e.g. to the [contact form](https://design.smart.coop/contact-form.html) then to the [subscription form](https://design.smart.coop/subscription-form.html), a vertical scrollbar appears. In the future this may cause the layout of similar pages to change their respective width, causing some visual differences.

Should we always display the scrollbar, even when the page is not tall enough to require one, to avoid those width differences ?

**Comment by Wolfr** [comment]
This article on CSS tricks discusses this problem: https://css-tricks.com/scrollbar-reflowing/

**Comment by Wolfr** [comment]
I think the conclusion is that we have to wait for the platform to fix this, as any other solution to try and fix this is fiddly/hacky and will solve things for one browser and then break it for another.
