### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Wolfr** [smartcoop/design#9]
This issue to track the changelog. We plan to make a page with similar content structure as screenshot below.

<img width="974" alt="Screen Shot 2021-07-29 at 17 36 44" src="https://user-images.githubusercontent.com/12690/127521839-d1a28c23-3c57-4582-abe5-7d6baad250a8.png">

**Comment by thusc** [comment]
So the changelog is done manually and being taken care of right now, so I'll close this issue.
